#!/usr/bin/env python3
"""judge_feature_hypotheses.py

Run independent judging/scoring for feature hypotheses generated by clinical_agent.py.

This script is intentionally decoupled from generation. It reads an existing
hypotheses JSON and writes judge outputs in the same format used previously:
- <base>_judge_original.json
- <base>_judge_revised.json (if revised hypotheses are provided/found)

Examples:
  python judge_feature_hypotheses.py \
    --hypotheses_json docs/agent/ist3/gpt-5-mini/with_shap_drlearner/hypotheses.json \
    --shap_json results/ist3/shapley/ist3_shap_summary_False.json \
    --trial_name ist3 \
    --model gpt-5

  python judge_feature_hypotheses.py \
    --hypotheses_json docs/agent/ist3/gpt-5-mini/simple_cot/hypotheses.json \
    --trial_name ist3 \
    --model gpt-5-mini \
    --api_provider openrouter
"""

import argparse
import json
import os
from typing import List, Literal, Optional

from openai import OpenAI
from pydantic import BaseModel, Field
from src.agent_schemas import ArticleExtraction
from src.agent_utils import (
    _convert_hypogenic_to_feature_format,
    _is_hypogenic_format,
    get_model_client,
    get_trial_metadata,
    infer_revised_path,
    load_json_file,
    load_local_env,
    load_top_features,
    map_feature_label,
    search_and_extract_article,
    write_json_file,
)


class MechanismScore(BaseModel):
    mechanism_type: str = Field(..., description="Type of mechanism being scored")
    plausibility: int = Field(
        ...,
        ge=1,
        le=5,
        description="Plausibility (1-5): how believable is this mechanism",
    )
    evidence_support: int = Field(
        ...,
        ge=1,
        le=5,
        description="Evidence support (1-5): how well is this mechanism supported by evidence",
    )
    specificity: int = Field(
        ...,
        ge=1,
        le=5,
        description="Specificity (1-5): how specific and detailed is the mechanism description",
    )
    testability: int = Field(
        ...,
        ge=1,
        le=5,
        description="Testability (1-5): how testable/falsifiable is this mechanism",
    )
    novelty: int = Field(
        ...,
        ge=1,
        le=5,
        description="Novelty (1-5): originality of this specific mechanism explanation",
    )
    overall_score: int = Field(
        ..., ge=1, le=5, description="Overall score (1-5) for this mechanism"
    )
    comments: str = Field(
        ..., description="Brief comments on this mechanism's strengths and weaknesses"
    )


class FeatureHypothesisScoreWithMechanisms(BaseModel):
    feature_name: str = Field(..., description="Feature being scored")
    hypothesis_id: Optional[str] = Field(
        None,
        description="Unique identifier for this hypothesis (used when multiple hypotheses target the same feature)",
    )
    per_mechanism_scores: List[MechanismScore] = Field(
        ..., description="Scores for each individual mechanism"
    )
    mechanism_plausibility: int = Field(
        ...,
        ge=1,
        le=5,
        description="Mechanism plausibility (1-5): biological/clinical coherence of proposed mechanisms",
    )
    clinical_interpretation: int = Field(
        ...,
        ge=1,
        le=5,
        description="Clinical interpretation (1-5): accuracy and clarity of what the feature represents",
    )
    evidence_alignment: int = Field(
        ...,
        ge=1,
        le=5,
        description="Alignment with existing literature (1-5): how well grounded in published clinical evidence",
    )
    subgroup_implications: int = Field(
        ...,
        ge=1,
        le=5,
        description="Subgroup implications (1-5): clarity and usefulness of suggested subgroups",
    )
    validation_plan_quality: int = Field(
        ...,
        ge=1,
        le=5,
        description="Validation quality (1-5): concreteness and appropriateness of validation suggestions",
    )
    caveat_awareness: int = Field(
        ...,
        ge=1,
        le=5,
        description="Caveat awareness (1-5): thoroughness in acknowledging limitations and alternatives",
    )
    novelty: int = Field(
        ...,
        ge=1,
        le=5,
        description="Novelty (1-5): originality and potential for new insights beyond existing literature",
    )
    overall_score: int = Field(
        ..., ge=1, le=5, description="Overall score (1-5): holistic assessment"
    )
    strengths: List[str] = Field(..., description="Key strengths")
    weaknesses: List[str] = Field(..., description="Key weaknesses")
    recommendation: Literal[
        "high_priority", "medium_priority", "low_priority", "reconsider"
    ] = Field(..., description="Recommendation for follow-up")
    justification: str = Field(
        ..., description="Brief justification for scores and recommendation"
    )


class FeatureJudgeOutput(BaseModel):
    summary: str = Field(
        ..., description="Overall assessment summary across all feature hypotheses"
    )
    scored_features: List[FeatureHypothesisScoreWithMechanisms]
    top_features: List[str] = Field(
        ..., description="Names of top-ranked features (by overall_score)"
    )
    methodological_concerns: Optional[List[str]] = Field(
        None, description="Any cross-cutting concerns about the analysis"
    )


def _build_study_context(
    hypotheses_payload: dict,
    treatment: str,
    outcome: str,
    population: str,
    evidence: dict,
) -> dict:
    feature_hypotheses = hypotheses_payload.get("feature_hypotheses", [])
    n_features = hypotheses_payload.get("n_unique_features", len({f.get("feature_name") for f in feature_hypotheses}))
    n_hypotheses_per_feature = hypotheses_payload.get("n_hypotheses_per_feature", 0)
    if not n_hypotheses_per_feature and feature_hypotheses:
        n_hypotheses_per_feature = max(
            len((feature_hypotheses[0] or {}).get("mechanisms", []) or []),
            0,
        )

    return {
        "dataset": hypotheses_payload.get("dataset", evidence.get("dataset", "unknown_dataset")),
        "learner": hypotheses_payload.get("learner", "unknown_learner"),
        "population": population,
        "treatment": treatment,
        "outcome": outcome,
        "source_explainer": hypotheses_payload.get("source_explainer", evidence.get("explainer", "unknown_explainer")),
        "n_hypotheses_per_feature": n_hypotheses_per_feature,
        "n_features": n_features,
        "available_features": evidence.get("available_features", []),
    }


def _normalize_feature_names_for_judge(hypotheses_payload: dict, dataset_name: Optional[str]) -> None:
    """Map raw feature names to clinician-readable labels in-place for judge scoring.

    This only affects what is sent to the judge and does not modify source hypothesis files.
    """
    feature_hypotheses = hypotheses_payload.get("feature_hypotheses") or []
    for feature_item in feature_hypotheses:
        if not isinstance(feature_item, dict):
            continue
        raw_name = feature_item.get("feature_name")
        if not isinstance(raw_name, str) or not raw_name.strip():
            continue
        feature_item["feature_name"] = map_feature_label(raw_name, dataset_name)


def score_feature_hypotheses(
    hypotheses: list,
    study_context: dict,
    evidence: dict,
    client: OpenAI,
    model_name: str,
    article_extraction: Optional[ArticleExtraction] = None,
    is_revised: bool = False,
) -> Optional[FeatureJudgeOutput]:
    """Score feature hypotheses using an independent judge."""
    judge_system = (
        "You are an independent scientific judge for mechanistic hypotheses.\n"
        "Evaluate each hypothesis on multiple dimensions using a 1-5 scale.\n"
        "Be objective, fair, and constructive.\n"
        "\n"
        "IMPORTANT: Score EACH hypothesis entry INDIVIDUALLY. Entries may share the same\n"
        "feature_name when multiple hypotheses target the same feature (e.g. different subgroups).\n"
        "In your output, copy the 'hypothesis_id' field from each input entry so every scored\n"
        "result can be traced back to its source hypothesis.\n"
        "\n"
        "Each hypothesis includes an 'importance_rank' field (1=most important feature).\n"
        "When evaluating Evidence Alignment, consider whether the RELATIVE RANKING aligns with\n"
        "clinical knowledge. Features ranked higher should be more established effect modifiers\n"
        "according to literature. A mismatch between model ranking and clinical knowledge should\n"
        "lower the Evidence Alignment score.\n"
        "\n"
        "SCORING CRITERIA:\n"
        "\n"
        "1. Mechanism Plausibility (1-5):\n"
        "   - Biological/physiological coherence of proposed mechanisms\n"
        "   - Consistency with established pathophysiology and pharmacology\n"
        "   - Specificity to the treatment and outcome context\n"
        "   - Avoidance of generic mechanisms that could apply to any feature\n"
        "   Score 5: Strong biological basis, well-established pathways, specific to context\n"
        "   Score 3: Reasonable but speculative, some supporting literature, moderately specific\n"
        "   Score 1: Implausible, contradicts known biology, purely generic\n"
        "\n"
        "2. Evidence Alignment (1-5):\n"
        "   - Feature importance: Whether identified features are known effect modifiers from published trials\n"
        "   - Ranking accuracy: Does the feature's importance_rank align with clinical literature?\n"
        "     * Higher-ranked features (rank 1, 2, 3) should be well-established modifiers\n"
        "     * Lower-ranked features may be plausible but less critical\n"
        "     * Penalize if a weakly-supported feature ranks above a well-established one\n"
        "     * Penalize if proposed features were not measured/available in the original trial\n"
        "   - Correctness of feature selection/ranking based on existing clinical literature\n"
        "   - Consistency with meta-analyses and systematic reviews on treatment heterogeneity\n"
        "   - Mechanistic grounding: Citations and references to established treatment effect heterogeneity\n"
        "   - Connection to known biological markers and risk stratification literature\n"
        "   - Appropriate recognition when evidence is sparse or speculative\n"
        "   Score 5: Feature is a well-established modifier AND ranking position matches clinical importance\n"
        "   Score 3: Plausible modifier with some literature support, OR ranking doesn't match expected clinical priority\n"
        "   Score 1: Unlikely modifier, contradicts literature, OR inappropriate ranking (weak feature ranked too high)\n"
        "\n"
        "3. Subgroup Implications (1-5):\n"
        "   - Clarity and actionability of proposed subgroups\n"
        "   - Feasibility of defining subgroups in practice (available data, clear cutpoints)\n"
        "   - Clinical utility - would these subgroups inform treatment decisions?\n"
        "   - Avoidance of arbitrary or clinically meaningless stratifications\n"
        "   Score 5: Clear, actionable, clinically meaningful subgroups\n"
        "   Score 3: Reasonable but vague or difficult to operationalize\n"
        "   Score 1: Unclear, arbitrary, or clinically meaningless\n"
        "\n"
        "4. Caveat Awareness (1-5):\n"
        "   - Thoroughness in acknowledging limitations and alternative explanations\n"
        "   - Recognition of potential confounding, bias, measurement error\n"
        "   - Appropriate epistemic humility (avoiding overclaiming)\n"
        "   - Acknowledgment when evidence is weak or mechanisms speculative\n"
        "   Score 5: Comprehensive caveats, honest about limitations\n"
        "   Score 3: Some caveats but incomplete or superficial\n"
        "   Score 1: Overclaiming, ignoring limitations, false certainty\n"
        "\n"
        "5. Novelty (1-5):\n"
        "   - Originality of the hypothesis beyond existing clinical literature\n"
        "   - Potential to generate new insights or challenge existing paradigms\n"
        "   - Whether the hypothesis identifies underexplored treatment effect modifiers\n"
        "   - Balance between novelty and plausibility (novel but not implausible)\n"
        "   Score 5: Highly original, identifies underexplored mechanisms, potential paradigm shift\n"
        "   Score 3: Moderately novel, extends existing knowledge in meaningful ways\n"
        "   Score 1: Reiterates well-established findings, no new insights\n"
        "\n"
        "For EACH individual mechanism, also score (1-5 scale):\n"
        "- Plausibility (1-5): biological believability of this specific mechanism\n"
        "- Evidence support (1-5): how well clinical literature supports this mechanism\n"
        "- Specificity (1-5): how detailed and connected to clinical/biological reasoning\n"
        "- Testability (1-5): how testable/falsifiable with available data and methods\n"
        "- Novelty (1-5): originality and uniqueness of this mechanism explanation\n"
        "- Overall score (1-5): holistic assessment of this mechanism\n"
        "- Brief comments: strengths, weaknesses, any concerns\n"
        "\n"
        "If original trial article context is provided, use it to:\n"
        "- Assess mechanism plausibility based on trial physiology\n"
        "- Judge interpretation accuracy against population characteristics\n"
        "- Evaluate validation feasibility given trial design\n"
        "- Cross-check if proposed mechanisms contradict known trial findings\n"
        "\n"
        "Provide honest, rigorous critique in strengths/weaknesses. Use the full 1-5 range."
    )

    judge_prompt = {
        "evidence": {
            "study_context": study_context,
        },
        "feature_hypotheses_to_score": hypotheses,
        "scoring_instructions": {
            "be_objective": True,
            "score_range": "1-5 for each dimension",
            "provide_justification": True,
        },
    }

    if is_revised:
        judge_prompt["scoring_instructions"]["note"] = "These are REVISED hypotheses after verification"

    if article_extraction is not None:
        judge_prompt["trial_article_context"] = article_extraction.model_dump()
        judge_prompt["scoring_instructions"]["use_article_context"] = (
            "Use trial article context to inform scoring, especially for "
            "mechanism plausibility and clinical interpretation accuracy."
        )

    try:
        result = client.beta.chat.completions.parse(
            model=model_name,
            messages=[
                {"role": "system", "content": judge_system},
                {"role": "user", "content": json.dumps(judge_prompt, indent=2)},
            ],
            response_format=FeatureJudgeOutput,
        )
        return result.choices[0].message.parsed
    except Exception as e:
        print(f"Error scoring feature hypotheses: {e}")
        return None


def main() -> None:
    load_local_env()

    parser = argparse.ArgumentParser()
    parser.add_argument("--hypotheses_json", required=True, help="Path to original hypotheses JSON")
    parser.add_argument("--revised_json", help="Optional path to revised hypotheses JSON")
    parser.add_argument("--shap_json", help="Optional SHAP summary JSON used for evidence context")

    parser.add_argument("--trial_name", help="Trial name (ist3, crash_2, sprint, accord, txa)")
    parser.add_argument("--treatment", help="Manual treatment override")
    parser.add_argument("--outcome", help="Manual outcome override")
    parser.add_argument("--population", help="Manual population override")
    parser.add_argument("--dataset", help="Optional dataset override")

    parser.add_argument("--model", default="gpt-5-mini", help="Judge model")
    parser.add_argument(
        "--api_provider",
        default="openai",
        choices=["openai", "openrouter"],
        help="API provider",
    )
    parser.add_argument("--api_base_url", help="Optional custom API base URL")
    parser.add_argument(
        "--retrieve_article",
        action="store_true",
        help="Retrieve trial article context (requires --trial_name)",
    )

    parser.add_argument("--out_judge_original", help="Output path for original judge JSON")
    parser.add_argument("--out_judge_revised", help="Output path for revised judge JSON")

    args = parser.parse_args()

    if not os.path.exists(args.hypotheses_json):
        parser.error(f"hypotheses file not found: {args.hypotheses_json}")

    revised_path = args.revised_json or infer_revised_path(args.hypotheses_json)

    hypotheses_payload = load_json_file(args.hypotheses_json)
    if _is_hypogenic_format(hypotheses_payload):
        hypotheses_payload = _convert_hypogenic_to_feature_format(hypotheses_payload)
    revised_payload = load_json_file(revised_path) if revised_path and os.path.exists(revised_path) else None
    if revised_payload and _is_hypogenic_format(revised_payload):
        revised_payload = _convert_hypogenic_to_feature_format(revised_payload)

    trial_meta = get_trial_metadata(args.trial_name) if args.trial_name else None

    treatment = args.treatment or (trial_meta["treatment"] if trial_meta else hypotheses_payload.get("treatment"))
    outcome = args.outcome or (trial_meta["outcome"] if trial_meta else hypotheses_payload.get("outcome"))
    population = args.population or (trial_meta["population"] if trial_meta else hypotheses_payload.get("population"))

    if not all([treatment, outcome, population]):
        parser.error(
            "Could not resolve treatment/outcome/population. Provide --trial_name or manual --treatment --outcome --population."
        )

    dataset_override = args.dataset or (args.trial_name.lower() if args.trial_name else hypotheses_payload.get("dataset"))

    _normalize_feature_names_for_judge(hypotheses_payload, dataset_override)
    if revised_payload is not None:
        _normalize_feature_names_for_judge(revised_payload, dataset_override)

    if args.shap_json and os.path.exists(args.shap_json):
        evidence = load_top_features(
            args.shap_json,
            n_features=max(1, len(hypotheses_payload.get("feature_hypotheses", []))),
            dataset_override=dataset_override,
        )
    else:
        evidence = {
            "dataset": dataset_override or hypotheses_payload.get("dataset", "unknown_dataset"),
            "learner": hypotheses_payload.get("learner", "unknown_learner"),
            "explainer": hypotheses_payload.get("source_explainer", "unknown_explainer"),
            "top_feature_evidence": [],
            "available_features": [],
        }

    client = get_model_client(args.api_provider, args.api_base_url)

    article_extraction = None
    if args.retrieve_article:
        if not args.trial_name:
            print("Warning: --retrieve_article requires --trial_name. Skipping article retrieval.")
        else:
            article_query = trial_meta.get("article_query", f"{args.trial_name} clinical trial")
            print(f"Retrieving article information for {args.trial_name}...")
            article_extraction = search_and_extract_article(article_query, args.trial_name, client, model_name=args.model)
            if article_extraction:
                print("Successfully extracted article information.")

    study_context = _build_study_context(
        hypotheses_payload=hypotheses_payload,
        treatment=treatment,
        outcome=outcome,
        population=population,
        evidence=evidence,
    )

    base, ext = os.path.splitext(args.hypotheses_json)
    out_judge_original = args.out_judge_original or f"{base}_judge_original{ext}"
    out_judge_revised = args.out_judge_revised or f"{base}_judge_revised{ext}"

    print("Scoring original feature hypotheses...")
    judge_report = score_feature_hypotheses(
        hypotheses=hypotheses_payload.get("feature_hypotheses", []),
        study_context=study_context,
        evidence=evidence,
        client=client,
        model_name=args.model,
        article_extraction=article_extraction,
        is_revised=False,
    )

    if judge_report is None:
        raise RuntimeError("Failed to generate judge report for original hypotheses")

    write_json_file(out_judge_original, judge_report.model_dump())
    print(f"Wrote judge report (original) to: {out_judge_original}")

    if revised_payload is not None:
        print("Scoring revised feature hypotheses...")
        judge_report_revised = score_feature_hypotheses(
            hypotheses=revised_payload.get("feature_hypotheses", []),
            study_context=study_context,
            evidence=evidence,
            client=client,
            model_name=args.model,
            article_extraction=article_extraction,
            is_revised=True,
        )
        if judge_report_revised is None:
            raise RuntimeError("Failed to generate judge report for revised hypotheses")

        write_json_file(out_judge_revised, judge_report_revised.model_dump())
        print(f"Wrote judge report (revised) to: {out_judge_revised}")


if __name__ == "__main__":
    main()
